twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '%menu%'
        host: '%host%'
        ga_tracking: G-00000000
    form_themes:
        - 'admin/form/editorjs_widget.html.twig'

when@test:
    twig:
        strict_variables: true
