twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '%menu%'
        host: '%host%'
        ya_metrika: '%env(YA_METRIKA)%'
    form_themes:
        - 'admin/form/editorjs_widget.html.twig'

when@test:
    twig:
        strict_variables: true
