server {
    listen 80;
    server_name nginx;
    access_log /home/logs/access_log main;
    client_max_body_size 10M;

    root /home/src/public;

    index index.php index.html;
        location / {
        try_files $uri /index.php$is_args$args;
    }

    location /build {
        expires 31536000;
    }

    location /uploads {
        expires 31536000;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }
}
