# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    maxFileSize: 2 #Mb
    uploadDirPath: '%kernel.project_dir%/public/uploads'
    uploadDirUrl: '/uploads'
    host: '%env(HOST)%'
    postsPerPage: 8
    siteName: 'Blog'
    feedbackRecipient: '%env(FEEDBACK_RECIPIENT)%'
    emailFrom: '%env(SMTP_SENDER)%'
    router.request_context.host: '%env(HOST)%'
    casesCategory: 'our-cases'
    menu:
        home:
            path: app_index_page
            title: Главная
        cases:
            path: app_our_cases_page
            title: Портфолио
        blog:
            path: app_blog_page
            title: Блог
        services:
            path: app_services_page
            title: Услуги
        products:
            path: app_products_page
            title: Продукты
        contacts:
            path: app_contacts_page
            title: Контакты

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    _instanceof:
        App\Editorjs\BlockParsers\BlockParser:
            tags: [ 'app.editorjs_parser_extension' ]

    App\Service\UniqueIdProvider:

    App\Service\UniqueIdProviderInterface:
        '@App\Service\UniqueIdProvider'

when@test:
    parameters:
        feedbackRecipient: 'test@example.com'
        emailFrom: 'test@example.com'
        host: 'https://host.example'
        postsPerPage: 2

    services:
        App\Tests\Utils\UniqueIdProviderStub:

        App\Service\UniqueIdProviderInterface:
            '@App\Tests\Utils\UniqueIdProviderStub'



when@prod:
    parameters:
        .container.dumper.inline_factories: true
